### ISSUE TITLE
download mseed data

### ISSUE THREAD

**Issue by mdenolle** [anowacki/Seis.jl#3] opened 2019-02-05 20:40 UTC
Hi Andy,

We would like to be able to download MSEED data . JPJones has written some of the functions we might need:
https://github.com/jpjones76/SeisIO.jl/blob/master/src/Types/SEED.jl
https://github.com/jpjones76/SeisIO.jl/blob/master/src/Web/IRIS.jl
https://github.com/jpjones76/SeisIO.jl/blob/master/src/Formats/mSEED.jl

Happy to chat more about it.
Marine

**Comment by anowacki** [comment] 2019-02-06 11:51
We should definitely leverage this existing work.  [SeisRequests](https://github.com/anowacki/SeisRequests.jl) can download arbitrary data including miniSEED into memory, so it would make sense to use [SeisIO](https://github.com/jpjones76/SeisIO) to parse the data and fill a `Trace` with the available information.

I do plan on implementing this at some point, but PRs to add this functionality would be very gratefully received!

I think in general there should be a constructor for `Trace`s which accepts a `Vector{UInt8}` of seismic data in an arbitrary format, and perhaps a keyword argument to set the format if not autodetected, returning possibly a single or array of `Trace`s.  `Seis.read` would then just call that.

In this case, I think that converting miniSEED data in memory may require some fairly low-level SeisIO interaction as the high-level [SeisIO.readmseed](https://github.com/jpjones76/SeisIO.jl/blob/29f6c795a0ff5d4f491dca00b41e288d344da193/src/Formats/mSEED.jl#L427) function assumes data on-disk.

**Comment by anowacki** [comment] 2019-02-07 11:44
I don't generally use miniSEED, but the first file I tried on my computer does this:

```julia
julia> using SeisIO

julia> readmseed("/opt/passcal/contrib/libmseed/example/test.mseed")
ERROR: No support for Blockette Type 0
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] parserec!(::SeisData, ::IOStream, ::Int64) at /Users/nowacki/.julia/packages/SeisIO/LHDKu/src/Formats/mSEED.jl:233
 [3] parsemseed!(::SeisData, ::IOStream, ::Int64) at /Users/nowacki/.julia/packages/SeisIO/LHDKu/src/Formats/mSEED.jl:392
 [4] #readmseed#193(::Bool, ::Int64, ::Function, ::String) at /Users/nowacki/.julia/packages/SeisIO/LHDKu/src/Formats/mSEED.jl:437
 [5] readmseed(::String) at /Users/nowacki/.julia/packages/SeisIO/LHDKu/src/Formats/mSEED.jl:428
 [6] top-level scope at none:0
```

Not sure if this will be an issue for miniSEED downloaded from IRIS.  Adding blockette 0 support to SeisIO would I'm sure be appreciated.

It may make sense to just call ObsPy via PyCall for now, but that will come with some speed penalty, or perhaps look into wrapping [libmseed](https://github.com/iris-edu/libmseed).

**Comment by mdenolle** [comment] 2019-02-07 11:46
Hi Andy,

We are going to try to import the functions from seisIO into your module, ideally we would move away from trying to use python module. More soon.
marine

**Comment by anowacki** [comment] 2019-02-07 17:21
I've added a trial implementation in the [`miniseed`](https://github.com/anowacki/Seis.jl/branch/miniseed) branch, which adds the `parse_mseed()` function.  This will parse the `.body` of a `HTTP.Messages.Response`, as returned by `SeisRequests.get_request` when asking for seismic data in miniSEED format.

This might be useful to benchmark against the SeisIO-based version.

**Comment by jpjones76** [comment] 2019-02-13 01:29
Hi everyone. I'll look into the unsupported blockette type. I don't yet support every Seed blockette type, so this could be an unsupported type with a wrong error message to STDOUT; it might also be something else, though. Could you open an issue in SeisIO with the exact steps to reproduce it? Please include your OS and Julia version? Thank you.

**Comment by jpjones76** [comment] 2019-02-13 08:43
Hi everyone, 

Are you sure your version of SeisIO is current? The bug looks like a duplicate of https://github.com/jpjones76/SeisIO.jl/issues/4, which I fixed 2018-12-20. The commands in anowacki's comment from 6 days ago work perfectly for me:

> $ git clone https://github.com/iris-edu/libmseed
> $ julia
> julia> using SeisIO
> julia> readmseed("/data/Code/src/libmseed/example/test.mseed")
> SeisData with 1 channels (1 shown)
> "    ID: IU.COLA.00.LHZ                                                                    " => ""
>           ...                                                                             
> (v1.0) pkg> status
>   ...
>   [e2f1b5a8] SeisIO v0.0.0 #master (https://github.com/jpjones76/SeisIO.jl)

Thanks for calling this to my attention.

**Comment by anowacki** [comment] 2020-05-18 07:29
Miniseed reading added in 0baf1fdf877459d2200da8657ed70c56b794673d

**Closed by anowacki** 2020-05-18 07:29 UTC
